### ISSUE TITLE
Error loading (RetroClashCore)

### ISSUE THREAD

**Issue by TrrIx** [RetroClash/RetroClash#4]
When i open the project with Microsoft Visual Studio 2015,
it says "At least one project folder could not be loaded".

I expected that all project maps will be loaded

*Screenshot*
https://ibb.co/eZ8t08

Dont know what you mean with Desktop
Browser: Chrome
Chrome Version: 67.0.3396.62

Best regards
TrIx

**Comment by Incrediblee** [comment]
Visual Studio 2017 with .NET Core 2.0 should be used. There may me problems with VS 2015.

**Comment by TrrIx** [comment]
Thank you its working! And i thought you cant code xD

**Comment by Incrediblee** [comment]
Danke, freut mich.
