### ISSUE TITLE
Working Levels and Eperiences

### ISSUE THREAD

**Issue by TrrIx** [RetroClash/RetroClash#5]
Liebes RetroClash Team,
Ich wünsche mir funktionierende Level und Experiences

1. Funktionierende Level
Sprich dass wenn man disconnect dass das Spieler Level nicht
auf 100 zurückgesetzt wird.
 2. Funktionierende Eperiences
Das gleiche wie bei den Leveln, wenn man reconnect dass
die Experiences nicht auf 0 resetet werden.

Liebe grüße 
TrIx

**Comment by Incrediblee** [comment]
Leider wurde das Projekt momentan stillgelegt da es alleine ein zu großer Zeitaufwand ist.
