### ISSUE TITLE
How can i edit apk to connect to server?

### ISSUE THREAD

**Issue by HerryYT** [RetroClash/RetroClash#6]

**Comment by HerryYT** [comment]
> On rooted devices simply use the Hosts Editor to "gamea.clashofclans.com" and to the ip of your server.
> If you don't have any rooted device you can change the hostname in the libg.so files from the apk with an APK Editor.

i tried to edit the hostname in the apk, but with notepad++ search i'm not able to find gamea.clashofclans.com, so i have no idea how to do that. Can you try yourself and after say if you find that because i tried with different apks but nothing. Thank you!

**Comment by Incr3dible** [comment]
You better use HxD to find the hostname. (it's free)

**Comment by Incr3dible** [comment]
And yes I have discord. 
Incredible#2109

**Comment by HerryYT** [comment]
HerryYT#3383  add me, anyways HxD cannot find the string too.. https://imgur.com/a/iXe4s8G

**Comment by Incr3dible** [comment]
Added you
